# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vehicle_force_msgs/VehicleForce.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class VehicleForce(genpy.Message):
  _md5sum = "c2afff5c6ed09aa9fbd688ff68067a55"
  _type = "vehicle_force_msgs/VehicleForce"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# This message decribes the forces of vehicle from road

float32 frontlateralforce
float32 frontslipangle
float32 rearlateralforce
float32 rearslipangle
float32 frontlongitudinalforce
float32 rearlongitudinalforce
float32 vxdot
float32 deltadot
"""
  __slots__ = ['frontlateralforce','frontslipangle','rearlateralforce','rearslipangle','frontlongitudinalforce','rearlongitudinalforce','vxdot','deltadot']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       frontlateralforce,frontslipangle,rearlateralforce,rearslipangle,frontlongitudinalforce,rearlongitudinalforce,vxdot,deltadot

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VehicleForce, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.frontlateralforce is None:
        self.frontlateralforce = 0.
      if self.frontslipangle is None:
        self.frontslipangle = 0.
      if self.rearlateralforce is None:
        self.rearlateralforce = 0.
      if self.rearslipangle is None:
        self.rearslipangle = 0.
      if self.frontlongitudinalforce is None:
        self.frontlongitudinalforce = 0.
      if self.rearlongitudinalforce is None:
        self.rearlongitudinalforce = 0.
      if self.vxdot is None:
        self.vxdot = 0.
      if self.deltadot is None:
        self.deltadot = 0.
    else:
      self.frontlateralforce = 0.
      self.frontslipangle = 0.
      self.rearlateralforce = 0.
      self.rearslipangle = 0.
      self.frontlongitudinalforce = 0.
      self.rearlongitudinalforce = 0.
      self.vxdot = 0.
      self.deltadot = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8f().pack(_x.frontlateralforce, _x.frontslipangle, _x.rearlateralforce, _x.rearslipangle, _x.frontlongitudinalforce, _x.rearlongitudinalforce, _x.vxdot, _x.deltadot))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.frontlateralforce, _x.frontslipangle, _x.rearlateralforce, _x.rearslipangle, _x.frontlongitudinalforce, _x.rearlongitudinalforce, _x.vxdot, _x.deltadot,) = _get_struct_8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8f().pack(_x.frontlateralforce, _x.frontslipangle, _x.rearlateralforce, _x.rearslipangle, _x.frontlongitudinalforce, _x.rearlongitudinalforce, _x.vxdot, _x.deltadot))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.frontlateralforce, _x.frontslipangle, _x.rearlateralforce, _x.rearslipangle, _x.frontlongitudinalforce, _x.rearlongitudinalforce, _x.vxdot, _x.deltadot,) = _get_struct_8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8f = None
def _get_struct_8f():
    global _struct_8f
    if _struct_8f is None:
        _struct_8f = struct.Struct("<8f")
    return _struct_8f
