# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from observer_msgs/observer.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class observer(genpy.Message):
  _md5sum = "e2f52368ad4e8041253811aff6250629"
  _type = "observer_msgs/observer"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

float64 des_steering_angle
float64 cur_steering_angle

float64 lateral_error
float64 heading_error

float64 linear_v_x
float64 linear_v_y
float64 linear_v_z

float64 angular_v_x
float64 angular_v_y
float64 angular_v_z

float64 position_x
float64 position_y
float64 position_z

float64 acc_x
float64 acc_y
float64 acc_z

float32 time_cost

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','des_steering_angle','cur_steering_angle','lateral_error','heading_error','linear_v_x','linear_v_y','linear_v_z','angular_v_x','angular_v_y','angular_v_z','position_x','position_y','position_z','acc_x','acc_y','acc_z','time_cost']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,des_steering_angle,cur_steering_angle,lateral_error,heading_error,linear_v_x,linear_v_y,linear_v_z,angular_v_x,angular_v_y,angular_v_z,position_x,position_y,position_z,acc_x,acc_y,acc_z,time_cost

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(observer, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.des_steering_angle is None:
        self.des_steering_angle = 0.
      if self.cur_steering_angle is None:
        self.cur_steering_angle = 0.
      if self.lateral_error is None:
        self.lateral_error = 0.
      if self.heading_error is None:
        self.heading_error = 0.
      if self.linear_v_x is None:
        self.linear_v_x = 0.
      if self.linear_v_y is None:
        self.linear_v_y = 0.
      if self.linear_v_z is None:
        self.linear_v_z = 0.
      if self.angular_v_x is None:
        self.angular_v_x = 0.
      if self.angular_v_y is None:
        self.angular_v_y = 0.
      if self.angular_v_z is None:
        self.angular_v_z = 0.
      if self.position_x is None:
        self.position_x = 0.
      if self.position_y is None:
        self.position_y = 0.
      if self.position_z is None:
        self.position_z = 0.
      if self.acc_x is None:
        self.acc_x = 0.
      if self.acc_y is None:
        self.acc_y = 0.
      if self.acc_z is None:
        self.acc_z = 0.
      if self.time_cost is None:
        self.time_cost = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.des_steering_angle = 0.
      self.cur_steering_angle = 0.
      self.lateral_error = 0.
      self.heading_error = 0.
      self.linear_v_x = 0.
      self.linear_v_y = 0.
      self.linear_v_z = 0.
      self.angular_v_x = 0.
      self.angular_v_y = 0.
      self.angular_v_z = 0.
      self.position_x = 0.
      self.position_y = 0.
      self.position_z = 0.
      self.acc_x = 0.
      self.acc_y = 0.
      self.acc_z = 0.
      self.time_cost = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_16df().pack(_x.des_steering_angle, _x.cur_steering_angle, _x.lateral_error, _x.heading_error, _x.linear_v_x, _x.linear_v_y, _x.linear_v_z, _x.angular_v_x, _x.angular_v_y, _x.angular_v_z, _x.position_x, _x.position_y, _x.position_z, _x.acc_x, _x.acc_y, _x.acc_z, _x.time_cost))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 132
      (_x.des_steering_angle, _x.cur_steering_angle, _x.lateral_error, _x.heading_error, _x.linear_v_x, _x.linear_v_y, _x.linear_v_z, _x.angular_v_x, _x.angular_v_y, _x.angular_v_z, _x.position_x, _x.position_y, _x.position_z, _x.acc_x, _x.acc_y, _x.acc_z, _x.time_cost,) = _get_struct_16df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_16df().pack(_x.des_steering_angle, _x.cur_steering_angle, _x.lateral_error, _x.heading_error, _x.linear_v_x, _x.linear_v_y, _x.linear_v_z, _x.angular_v_x, _x.angular_v_y, _x.angular_v_z, _x.position_x, _x.position_y, _x.position_z, _x.acc_x, _x.acc_y, _x.acc_z, _x.time_cost))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 132
      (_x.des_steering_angle, _x.cur_steering_angle, _x.lateral_error, _x.heading_error, _x.linear_v_x, _x.linear_v_y, _x.linear_v_z, _x.angular_v_x, _x.angular_v_y, _x.angular_v_z, _x.position_x, _x.position_y, _x.position_z, _x.acc_x, _x.acc_y, _x.acc_z, _x.time_cost,) = _get_struct_16df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_16df = None
def _get_struct_16df():
    global _struct_16df
    if _struct_16df is None:
        _struct_16df = struct.Struct("<16df")
    return _struct_16df
