(cl:in-package observer_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DES_STEERING_ANGLE-VAL
          DES_STEERING_ANGLE
          CUR_STEERING_ANGLE-VAL
          CUR_STEERING_ANGLE
          LATERAL_ERROR-VAL
          LATERAL_ERROR
          HEADING_ERROR-VAL
          HEADING_ERROR
          LINEAR_V_X-VAL
          LINEAR_V_X
          LINEAR_V_Y-VAL
          LINEAR_V_Y
          LINEAR_V_Z-VAL
          LINEAR_V_Z
          ANGULAR_V_X-VAL
          ANGULAR_V_X
          ANGULAR_V_Y-VAL
          ANGULAR_V_Y
          ANGULAR_V_Z-VAL
          ANGULAR_V_Z
          POSITION_X-VAL
          POSITION_X
          POSITION_Y-VAL
          POSITION_Y
          POSITION_Z-VAL
          POSITION_Z
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
          TIME_COST-VAL
          TIME_COST
))