sudo: required

services:
  - docker

# show correct language tag in Travis CI build.
language: cpp

env:
  matrix:
    - NAME: install_dependencies.sh
      WITH_ROS: false

before_install:
  # this cmd will run docker, and copy the contents of the repo root directory to /home/ivrcscripts folder
  # get the docker running
  - if [ $WITH_ROS == 'false' ]; then
      docker run -d -it --name ci_xenial -v $(pwd):/home/repo_dir aragdoll/docker_ubuntu:xenial;
    else
      docker run -d -it --name ci_xenial_ros -v $(pwd):/home/repo_dir aragdoll/docker_ubuntu:xenial_ros_kinetic;
    fi

install:
  - if [ $WITH_ROS == 'false' ]; then
      docker exec -it ci_xenial /bin/bash -c "/home/repo_dir/script/$NAME";
    else
      docker exec -it ci_xenial_ros /bin/bash -c "/home/repo_dir/script/$NAME";
    fi

script:
  - if [ $WITH_ROS == 'false' ]; then
      docker exec -it ci_xenial /bin/bash -c "echo 'Xenial without ROS CI is working!'";
    else
      docker exec -it ci_xenial_ros /bin/bash -c "echo 'Xenial with ROS CI is working!'";
    fi


notifications:
    email: false
